set (CMAKE_BUILD_TYPE Release CACHE STRING "" FORCE)
set (CMAKE_CXX_FLAGS "-D_GLIBCXX_USE_CXX11_ABI=0 -pipe -fstack-protector-strong -O3 -march=native" CACHE STRING "" FORCE)
set (CMAKE_C_FLAGS "-pipe -fstack-protector-strong -O3 -march=native -mtune=native" CACHE STRING "" FORCE)
set (CMAKE_INSTALL_PREFIX /usr CACHE PATH "" FORCE)
set (BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set (gnuinstall ON CACHE BOOL "" FORCE)
set (roofit ON CACHE BOOL "" FORCE)
set (testing OFF CACHE BOOL "" FORCE)
set (castor OFF CACHE BOOL "" FORCE)
set (builtin_ftgl OFF CACHE BOOL "" FORCE)
set (builtin_freetype OFF CACHE BOOL "" FORCE)
set (builtin_glew OFF CACHE BOOL "" FORCE)
set (builtin_pcre OFF CACHE BOOL "" FORCE)
set (builtin_zlib OFF CACHE BOOL "" FORCE)
set (builtin_lzma OFF CACHE BOOL "" FORCE)
set (builtin_llvm ON CACHE BOOL "" FORCE)
set (cxx11 ON CACHE BOOL "" FORCE)
set (cling ON CACHE BOOL "" FORCE)
set (gsl_shared ON CACHE BOOL "" FORCE)
set (oracle OFF CACHE BOOL "" FORCE)
set (pythia8 ON CACHE BOOL "" FORCE)
set (shared ON CACHE BOOL "" FORCE)
set (xft ON CACHE BOOL "" FORCE)
set (x11 ON CACHE BOOL "" FORCE)
